version: "3"
services:
  influxdb:
    container_name: influxdb
    hostname: influxdb          
    image: quay.io/influxdb/influxdb:v2.0.3
    volumes:
      # Mount for influxdb data directory and configuration
      - .\influxDB:/root/.influxdbv2
    ports:
      - "8086:8086"
  # Use the influx cli to set up an influxdb instance.
  influxdb_cli:
    container_name: influxdb_cli
    hostname: influxdb_cli          
    links:
      - influxdb
    image: quay.io/influxdb/influxdb:v2.0.3
    # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
    entrypoint:
      influx setup --bucket dex -t OGymrpHW2WrG3pMwlGWQ2ZKtYJR5KxGoEFL -o zinnion --username=zinnion --password=Br@sa154 --host=http://influxdb:8086 -f
      # Wait for the influxd service in the influxdb container has fully bootstrapped before trying to setup an influxdb instance with the influxdb_cli service.
    restart: on-failure:10
    depends_on:
      - influxdb
  telegraf:
    image: telegraf
    links:
      - influxdb
    volumes:
      # Mount for telegraf config
      - .\telegraf.conf:/var/lib/influxdb
    depends_on:
      - influxdb_cli
volumes:
  influxdbv2:
